  platform :ios, '8.0'

# Uncomment this line if you're using Swift
# use_frameworks!

def common_pods
    
    # UI
    pod 'UIScrollView-InfiniteScroll'
    pod 'MBProgressHUD', '~> 0.9.2'
    
    # Networking
    pod 'AFNetworking', '~> 3.0'
    pod 'SDWebImage', '~>3.7'
    pod 'Reachability'
    
    # Data Models
    pod 'Mantle'
    
end

def testing_pods
    
    pod 'Specta'
    pod 'Expecta'
    pod 'OCMock'
    
end

target 'GitRepo' do
    common_pods
end

target 'GitRepoTests' do
    
    testing_pods
    common_pods
    
end

target 'GitRepoAcceptanceTests', :exclusive => true do
    
    testing_pods
    common_pods
    
    pod 'KIF', '~> 3.0', :configurations => ['Debug']
    
end

target 'GitRepoUITests' do 
    
end

