  platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'GitRepo' do
	# UI
	pod 'UIScrollView-InfiniteScroll'
    pod 'MBProgressHUD', '~> 0.9.2'

	# Networking
	pod 'AFNetworking', '~> 3.0'
	pod 'SDWebImage', '~>3.7'
    pod 'Reachability'

	# Data Models
	pod 'Mantle'

end

target 'GitRepoTests' do

end

target 'GitRepoUITests' do

end

